services:
  desktop:
    # This version comes with a Windows-like interface pre-themed
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspaces:cached
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TITLE=Windows 10 # Changes the browser tab title
    shm_size: "1gb"
