services:
  desktop:
    image: lscr.io/linuxserver/webtop:ubuntu-xfce
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspaces:cached
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    shm_size: "1gb"